[build]
  # 빌드 명령어 (단일 HTML 파일이므로 빌드 과정 없음)
  command = "echo 'No build process needed'"
  
  # 배포할 디렉토리
  publish = "."

[build.environment]
  # Node.js 버전 (필요시)
  NODE_VERSION = "18"

# 리다이렉트 규칙 (SPA 라우팅용, 필요시 사용)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 헤더 설정 (보안 강화)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://www.gstatic.com https://*.firebaseapp.com https://*.googleapis.com; script-src 'self' 'unsafe-inline' https://www.gstatic.com https://cdn.tailwindcss.com; style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com; font-src 'self' data:; img-src 'self' data: https:;"

# 캐시 설정
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
